import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Hello() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>Hello Page</h1>
        </div>
      </main>

    </div>
  )
}
