import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Base html element to give target="_blank" behaviour to all links in the page */}
      <base target="_blank" />

      <main className={styles.main}>
        <div>
          <Link href="/hello">
            Should open in new tab
          </Link>
        </div>

        <div style={{ marginTop: '40px' }}>
          <Link href="https://google.com">
            Link to external URL works properly
          </Link>
        </div>
      </main>
    </div>
  )
}
